"use client";
import { fetchCall, updateCall, logCourtPacket } from "../data";
import { genId, today } from "../utils";
import type { EvidenceItem } from "../types";
import { COURT_PACKET_EVIDENCE_TYPE } from "./sections";
import type { PacketResult } from "./generate";
import { uploadStaffFile } from "../staffStorage";

// Save a copy of exactly what was produced to the call's attached documents
// (the `evidence` bucket + the call's evidence list) so there's a durable
// record of the packet as generated, and so it can be emailed later.
// evidence is a private bucket — what's stored as the item's "url" here is
// really just the storage path; there is no standing public URL anymore.
export async function saveCopyToCall(callId: string, result: PacketResult, generatedBy: string, reason?: string): Promise<{ path: string; item: EvidenceItem }> {
  const path = `${callId}/court-packets/${crypto.randomUUID()}-${result.filename}`;
  const body = new Blob([result.bytes as unknown as BlobPart], { type: "application/pdf" });
  const up = await uploadStaffFile("evidence", path, body, { upsert: false, contentType: "application/pdf" });
  if (!up.ok) throw new Error(up.error);

  const item: EvidenceItem = {
    id: genId(),
    type: COURT_PACKET_EVIDENCE_TYPE,
    description: `Court Packet — ${result.pageCount} pages, generated by ${generatedBy}${reason ? ` (${reason})` : ""}`,
    file_name: result.filename,
    file_type: "application/pdf",
    url: path,
    file_url: path,
    notes: `Sections: ${result.sections.map((s) => `${s.label} (p.${s.startPage})`).join("; ")}`,
    date: today(),
  };
  // Re-read the call first so a packet saved seconds after someone else added
  // evidence appends to the latest list instead of overwriting it.
  const fresh = await fetchCall(callId);
  await updateCall(callId, { evidence: [...((fresh?.evidence || []) as EvidenceItem[]), item] });
  return { path, item };
}

export async function recordPacket(callId: string, result: PacketResult, generatedBy: string, reason?: string): Promise<void> {
  await logCourtPacket({
    dispatch_call_id: callId,
    generated_by: generatedBy,
    sections_included: result.sections.map((s) => ({ id: s.id, label: s.label, startPage: s.startPage, pages: s.pages })),
    page_count: result.pageCount,
    reason,
  });
}
