-- Medication Library
-- Run in production Supabase SQL editor.

CREATE TABLE IF NOT EXISTS medications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  unit TEXT,
  concentration TEXT,
  default_cost NUMERIC DEFAULT 0,
  species TEXT[] DEFAULT ARRAY['Dog','Cat','All'],
  dea_schedule TEXT,
  notes TEXT,
  active BOOLEAN DEFAULT true,
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE medications DISABLE ROW LEVEL SECURITY;

INSERT INTO medications (name, category, unit, concentration) VALUES
('Acepromazine 25mg tablets','Sedative','tablets','25mg'),
('Acepromazine injection','Sedative','ml','10mg/mL'),
('Afrin Nasal Drops','Other','drops',NULL),
('Albon Suspension','Antibiotic','ml',NULL),
('Amoxicillin 250mg','Antibiotic','capsules','250mg'),
('Amoxicillin 500mg','Antibiotic','capsules','500mg'),
('Amoxicillin 50mg/mL','Antibiotic','ml','50mg/mL'),
('Animax Ointment','Dermatological',NULL,NULL),
('Apoquel 16mg','Anti-inflammatory','tablets','16mg'),
('Azithromycin 250mg','Antibiotic','tablets','250mg'),
('Baytril 22.7mg','Antibiotic','tablets','22.7mg'),
('Baytril 68mg','Antibiotic','tablets','68mg'),
('Buprenorphine','Pain/Sedative','ml','0.3mg/mL'),
('Butorphanol','Pain/Sedative','ml','10mg/mL'),
('Carprofen 25mg','Anti-inflammatory','tablets','25mg'),
('Carprofen 75mg','Anti-inflammatory','tablets','75mg'),
('Cephalexin 250mg','Antibiotic','capsules','250mg'),
('Cephalexin 500mg','Antibiotic','capsules','500mg'),
('Chlorpheniramine','Antihistamine','tablets','4mg'),
('Clavamox 125mg','Antibiotic','tablets','125mg'),
('Clavamox 250mg','Antibiotic','tablets','250mg'),
('Clindamycin 150mg','Antibiotic','capsules','150mg'),
('Convenia Injection','Antibiotic','ml','80mg/mL'),
('Dexamethasone','Anti-inflammatory','ml','2mg/mL'),
('Dexdomitor','Sedative','ml','0.5mg/mL'),
('Diphenhydramine','Antihistamine','ml','50mg/mL'),
('Doxycycline 100mg','Antibiotic','tablets','100mg'),
('Doxycycline 50mg','Antibiotic','tablets','50mg'),
('Euthasol','DEA Controlled','ml','390mg/mL'),
('Famotidine 10mg','Gastrointestinal','tablets','10mg'),
('Fentanyl patch','Pain/DEA Controlled',NULL,NULL),
('Flagyl 250mg','Antibiotic','tablets','250mg'),
('Flagyl 500mg','Antibiotic','tablets','500mg'),
('Fluconazole 50mg','Antifungal','tablets','50mg'),
('Hydroxyzine 10mg','Antihistamine','tablets','10mg'),
('Hydroxyzine 25mg','Antihistamine','tablets','25mg'),
('Ivermectin 1%','Antiparasitic','ml','10mg/mL'),
('Ketamine','Sedative/DEA Controlled','ml','100mg/mL'),
('Meloxicam 1.5mg/mL','Anti-inflammatory','ml','1.5mg/mL'),
('Metronidazole 250mg','Antibiotic','tablets','250mg'),
('Metronidazole 500mg','Antibiotic','tablets','500mg'),
('Minocycline 100mg','Antibiotic','tablets','100mg'),
('Morphine','Pain/DEA Controlled','ml','15mg/mL'),
('NexGard','Antiparasitic',NULL,NULL),
('Nitenpyram','Antiparasitic','tablets',NULL),
('Ondansetron 4mg','Gastrointestinal','tablets','4mg'),
('Praziquantel','Antiparasitic','tablets',NULL),
('Prednisolone 5mg','Anti-inflammatory','tablets','5mg'),
('Prednisone 20mg','Anti-inflammatory','tablets','20mg'),
('Propofol','Sedative','ml','10mg/mL'),
('Pyrantel Pamoate','Antiparasitic','ml',NULL),
('Revolution Plus','Antiparasitic',NULL,NULL),
('Rimadyl 25mg','Anti-inflammatory','tablets','25mg'),
('Rimadyl 75mg','Anti-inflammatory','tablets','75mg'),
('Ringer''s Lactate','Fluid','ml',NULL),
('Saline 0.9%','Fluid','ml',NULL),
('Sentinel','Antiparasitic',NULL,NULL),
('Simplicef 100mg','Antibiotic','tablets','100mg'),
('Simplicef 200mg','Antibiotic','tablets','200mg'),
('Telazol','Sedative/DEA Controlled','ml','100mg/mL'),
('Torbugesic','Pain/Sedative','ml','10mg/mL'),
('Tramadol 50mg','Pain','tablets','50mg'),
('Trazodone 100mg','Behavioral','tablets','100mg'),
('Trazodone 50mg','Behavioral','tablets','50mg'),
('Tri-Otic','Otic',NULL,NULL),
('Tylosin','Antibiotic','tablets',NULL),
('Vetmedin 1.25mg','Cardiac','tablets','1.25mg'),
('Vetmedin 5mg','Cardiac','tablets','5mg'),
('Xylazine 100mg/mL','Sedative','ml','100mg/mL'),
('Zofran 4mg','Gastrointestinal','tablets','4mg')
ON CONFLICT DO NOTHING;
